# Importing library

In [7]:
import numpy as np 

# Defining arrays

In [8]:
nary=np.array([1, 2, 3, 4, 5, 6, 7, 8,9, 10])
print(nary)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
nary*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
nd_2=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(nd_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#Three dimension array
nd_3=np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]])
print(nd_3)

# Using number dimension(ndim)

In [16]:
print(nary.ndim)

1


In [18]:
print(nd_2.ndim)

2


In [24]:
print(nd_3.ndim)

3


In [25]:
nd_5=np.array([1, 2, 3, 4, 5], ndmin=5)
print(nd_5)

[[[[[1 2 3 4 5]]]]]


# Calling/ Identifying objects using index

In [30]:
print(nary[4])

5


In [34]:
print([nary[3]*nary[6], nary[4]-nary[1]])

[28, 3]


In [35]:
print(nd_2[1,2])

8


In [43]:
print(nd_3[0,2,0])

11


# Negative indexing

In [45]:
print(nary[-1])

10


In [46]:
print(nd_3[-1,0,2])

3


# Slicing items in Variables/Elements

In [47]:
print(nary[1:4])

[2 3 4]


In [49]:
print(nary[4:])

[ 5  6  7  8  9 10]


In [54]:
print(nary[:7]) 

[1 2 3 4 5 6 7]


In [58]:
print(nd_2[0,1:4])

[2 3 4]


In [59]:
print(nd_3[0,1,1:4])

[7 8 9]
