# Importing Libraries

In [55]:
import numpy as np

import pandas as pd

# 1 a.Generating a 2 by 3 matrix and multiplying by a scalar of two

In [237]:
#Defining matrix
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [4]:
#Multiplying matrix'mat' by a scalar of 2
mat_1 = mat*2
print(mat_1)

[[ 2  4  6]
 [ 8 10 12]]


# b.Creating a 3 by 3 Identity matrix

In [5]:
mat_2 = np.identity(3, int)
print(mat_2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# c.Creating a 1-D array called arry1 and converting it to 3-D array

In [226]:
arry1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
print(arry1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
#Converting arry1 to 3-D array
arry2= np.array([[[0, 1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23, 24, 25, 26]]])
print(arry2) 

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]]


# d.Creating two 2-D arrays and Stacking them together both Horizontally and Vertically 

In [229]:
#Defining first 2-D array
my_mat = np.array([[1, 2, 3], [ 4, 5, 6]])
print(my_mat)

[[1 2 3]
 [4 5 6]]


In [231]:
#Defining second 2-D array
my_matrix = np.array([[7, 8, 9], [10, 11, 12]])
print(my_matrix)

[[ 7  8  9]
 [10 11 12]]


In [234]:
#Horizontally stacking arrays together
np.hstack([my_mat, my_matrix])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [235]:
#Vertically stacking arrays together
np.vstack([my_mat, my_matrix])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# e.Creating equally spaced sequence ranging from 0-100 with a gap of 5

In [225]:
sequence = np.arange(0,100,5)
sequence

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

# 2 a.Creating a DataFrame using a list of Students

In [19]:
#Defining list of Students
stu_list = (["Robert Addo", "Eunice Ansah", "Albert Okan","Christabel Asante", "Patience Oye"])

#Creating DataFrame using stu_list
students = pd.DataFrame(stu_list, columns=['Name of Students'])
print(students)

    Name of Students
0        Robert Addo
1       Eunice Ansah
2        Albert Okan
3  Christabel Asante
4       Patience Oye


# c.Creating a DataFrame Using a list of GPL teams and their goals scored for previous five matches

In [22]:
#Defining list of GPL teams and goals scored 
teamlist_of_GPL = (["Asante Kotoko", "Bechem United", "Great Olympics", "Aduana Stars", "King Faisal", "Medeama", "Hearts of Oak", "Karela", "Dreams", 
                   "Berekum Chelsea", "Ashanti Gold", "Legon Cities", "Tamale", "Bibiani Gold Stars", "Accra Lion", "WAFA", "Eleven Wonders", "Elmina Sharks"])

goals_scored = [7, 4, 4, 5, 3, 1, 1, 6, 6, 5, 9, 6, 3, 5, 4, 2, 2, 2]


In [23]:
#Defining a dictionary containing GPL teams and goals scored
dict_gpl = {'Ghana Premier League Teams':teamlist_of_GPL, 'Goals scored for the previous five matches':goals_scored}

#Creating a DataFrame from the dictionary
teams = pd.DataFrame(dict_gpl)
print(teams)

   Ghana Premier League Teams  Goals scored for the previous five matches
0               Asante Kotoko                                           7
1               Bechem United                                           4
2              Great Olympics                                           4
3                Aduana Stars                                           5
4                 King Faisal                                           3
5                     Medeama                                           1
6               Hearts of Oak                                           1
7                      Karela                                           6
8                      Dreams                                           6
9             Berekum Chelsea                                           5
10               Ashanti Gold                                           9
11               Legon Cities                                           6
12                     Tamale         

# c.Creating a DataFrame using list of West African Countries, Capital & Population

In [24]:
#list of West African Countries 
westafcount = (["Nigeria", "Ghana", "Ivory Coast", "Benin", "Guinea", "Mali", "Liberia", "Burkina Faso", "Senegal",
                "Niger", "Gambia", "Togo", "Mauritania", "Guinea-Bissau", "Sierra Leon", "Cameroon", "Equitorial Guinea"])

#list of West African Capitals
westafcap = (['Abudja', 'Accra', 'Abidjan', 'Porto-Novo', 'Conakry', 'Bamako', 'Monrovia', 'Ouagadougou', 'Daker', 
             'Niger', 'Banjul', 'Lome', 'Nouakcholl', 'Bissau', 'Freetown', 'Yaounde', 'Malabo'])

#list of West African Countries population
westafpop = [216746934, 32395450, 27742298, 12784726, 13865691, 21473764, 5305117, 22102838, 17653671,
             26083660, 2558482, 8680837, 4901981, 2063367, 8306436, 27623934, 1478271]

In [33]:
#Creating a dictionary from the lists
dict_count = {'West African Countries':westafcount, 'Capital':westafcap, 'Population(2022)':westafpop}

In [34]:
#Creating a DataFrame from the defined dictionary 
countries = pd.DataFrame(dict_count)
print(countries)

   West African Countries      Capital  Population(2022)
0                 Nigeria       Abudja         216746934
1                   Ghana        Accra          32395450
2             Ivory Coast      Abidjan          27742298
3                   Benin   Porto-Novo          12784726
4                  Guinea      Conakry          13865691
5                    Mali       Bamako          21473764
6                 Liberia     Monrovia           5305117
7            Burkina Faso  Ouagadougou          22102838
8                 Senegal        Daker          17653671
9                   Niger        Niger          26083660
10                 Gambia       Banjul           2558482
11                   Togo         Lome           8680837
12             Mauritania   Nouakcholl           4901981
13          Guinea-Bissau       Bissau           2063367
14            Sierra Leon     Freetown           8306436
15               Cameroon      Yaounde          27623934
16      Equitorial Guinea      

# d.A DataFrame showing GPL table

In [35]:
#Defining list of teams
teams = (["Hearts of Oak", "Asante Kotoko", "Ebusua Dwarfs", "Sekondi Hassacas", "Okuahu United", "Tano Bofoakwa", "BA United"])

#Defining list of goals for
goals_for = [120, 90, 90, 80, 78, 70, 71]

#Defining list of goals against
goals_against = [35, 55, 60, 43, 39, 50, 55]

#Defining list of team points
points = [80, 60, 60, 55, 53, 49, 44]

In [36]:
#Dictionary from the lists
dict_teams = {'Teams':teams, 'GF':goals_for, 'GA':goals_against, 'PTS':points}

In [38]:
#DataFrame created from the dictionary
leag_table = pd.DataFrame(dict_teams, index=['1', '2', '3', '4', '5', '6', '7'])
print(leag_table)

              Teams   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okuahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7         BA United   71  55   44


# i.Printing Team name, Goals For(GF), Goals Against(GA) and Points(PTS)

In [46]:
leag_table[['Teams', 'GF', 'GA', 'PTS']]

Teams   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okuahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7         BA United   71  55   44

## ii.Displaying details of the teams 

In [61]:
#Teams considered more than 30 goals 
leag_table.iloc[:, :] 

Teams   GF  GA  PTS
1     Hearts of Oak  120  35   80
2     Asante Kotoko   90  55   60
3     Ebusua Dwarfs   90  60   60
4  Sekondi Hassacas   80  43   55
5     Okuahu United   78  39   53
6     Tano Bofoakwa   70  50   49
7         BA United   71  55   44

In [59]:
#Teams scored less than 80 goals
leag_table.iloc[4:7, :]

Teams  GF  GA  PTS
5  Okuahu United  78  39   53
6  Tano Bofoakwa  70  50   49
7      BA United  71  55   44

In [62]:
#Teams that had less than 60 points
leag_table.iloc[3:7, :]

Teams  GF  GA  PTS
4  Sekondi Hassacas  80  43   55
5     Okuahu United  78  39   53
6     Tano Bofoakwa  70  50   49
7         BA United  71  55   44

## 3. Importing and working with csv file 

In [122]:
#Defining and reading your data set
cars = pd.read_csv('cars 2.csv',)
cars

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
..    ...         ...               ...         ...     ...         ...   
56     81      Toyota         Salon car        97.3   171.7         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0              four             7.4    33.79614   87717.5          NaN   
1              four             7.4    33.79614  107250.0          NaN   
2               six            10.3    30.57746  107250.0          NaN   
3              four             6.8    38.62416   90675.0          NaN   
4              five             7.7    28.96812  113425.0          NaN   
..              ...             ...         ...       ...          ...   
56             four             5.7    43.45218   51837.5          NaN   
57             four             3.5    59.54558   51967.5          NaN   
58             four             6.7    41.84284   64967.5          NaN   
59             four             7.6    37.01482   84110.0          NaN   
60             four             7.6    37.01482   87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0           NaN          NaN          NaN          NaN  
1           NaN          NaN          NaN          NaN  
2           NaN          NaN          NaN          NaN  
3           NaN          NaN          NaN          NaN  
4           NaN          NaN          NaN          NaN  
..          ...          ...          ...          ...  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN  

[61 rows x 15 columns]

# a.Printing the first five rows from the data set

In [64]:
cars.head()

index  company          car_type  wheel-base  length engine-type  \
0      0    Honda       Convertible        88.6   168.8        dohc   
1      1    Honda       Convertible        88.6   168.8        dohc   
2      2    Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      3  Hyundai         Salon car        99.8   176.6         ohc   
4      4  Hyundai         Salon car        99.4   176.6         ohc   

  num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0             four             7.4    33.79614   87717.5          NaN   
1             four             7.4    33.79614  107250.0          NaN   
2              six            10.3    30.57746  107250.0          NaN   
3             four             6.8    38.62416   90675.0          NaN   
4             five             7.7    28.96812  113425.0          NaN   

   Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN

# Printing the last five rows from the data set

In [65]:
cars.tail()

index     company   car_type  wheel-base  length engine-type  \
56     81      Toyota  Salon car        97.3   171.7         ohc   
57     82      Toyota  Salon car        97.3   171.7         ohc   
58     86      Toyota  Salon car        97.3   171.7         ohc   
59     87  Mitsubishi  Salon car       104.3   188.8         ohc   
60     88  Mitsubishi      Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km    price  Unnamed: 10  \
56             four             5.7    43.45218  51837.5          NaN   
57             four             3.5    59.54558  51967.5          NaN   
58             four             6.7    41.84284  64967.5          NaN   
59             four             7.6    37.01482  84110.0          NaN   
60             four             7.6    37.01482  87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN

# b.Cleaning the dataset and Updating the csv file

In [120]:
#Clearing all Unnamed columns
cars_clean = cars.dropna(axis='columns', how='all')
cars_clean

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
..    ...         ...               ...         ...     ...         ...   
56     81      Toyota         Salon car        97.3   171.7         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km     price  
0              four             7.4    33.79614   87717.5  
1              four             7.4    33.79614  107250.0  
2               six            10.3    30.57746  107250.0  
3              four             6.8    38.62416   90675.0  
4              five             7.7    28.96812  113425.0  
..              ...             ...         ...       ...  
56             four             5.7    43.45218   51837.5  
57             four             3.5    59.54558   51967.5  
58             four             6.7    41.84284   64967.5  
59             four             7.6    37.01482   84110.0  
60             four             7.6    37.01482   87197.5  

[61 rows x 10 columns]

In [88]:
#Clearing all NA from the dataset
cars_updated = cars_clean.dropna()
cars_updated

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
11     14         Bmw         Salon car       103.5   193.8         ohc   
12     15         Bmw         Salon car       110.0   197.0         ohc   
13     16     Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
27     36       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28     37       Mazda  Four Wheel Drive        93.1   159.1         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
31     43       Mazda         Salon car       104.9   175.0         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
35     47      Toyota           hardtop       112.0   199.2        ohcv   
36     49  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
48     66       Honda  Four Wheel Drive        95.7   158.7         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
55     80      Toyota        

In [98]:
#Saving updated csv to a new csv file
cars_updated.to_csv('Data/MyNewCSVFile.csv', index=False)

## c.Most expensive car company name

In [123]:
#Sorting company by price from dataset
cars_updated.sort_values(['company', 'price'], ascending = False,)

index     company          car_type  wheel-base  length engine-type  \
35     47      Toyota           hardtop       112.0   199.2        ohcv   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
33     45      Toyota             Wagon       110.0   190.9         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
56     81      Toyota         Salon car        97.3   171.7         ohc   
55     80      Toyota         Salon car        97.3   171.7         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
43     56      Nissan             Wagon        94.5   170.2         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
37     50  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
36     49  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
31     43       Mazda         Salon car       104.9   175.0         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28     37       Mazda  Four Wheel Drive        93.1   159.1         ohc   
27     36       Mazda  Four Wheel Drive        93.1   159.1         ohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
13     16     Kantaka  Four Wheel Drive        88.4   141.1           l   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
54     79       Honda             Wagon       104.5   187.8        dohc   
0       0       Honda       Convertible        88.6   168.8        dohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
48     66       Honda  Four Wheel Drive        95.7   158.7         ohc   
11     14         Bmw        

In [176]:
#Most expensive car company name
expcar_com = cars_updated.sort_values('price', ascending=False).head(1)
expcar_com

index company car_type  wheel-base  length engine-type num-of-cylinders  \
35     47  Toyota  hardtop       112.0   199.2        ohcv            eight   

    egine_capacity  average-km     price  
35            12.3    22.53076  295100.0

## d.Print all Kantaka Cars details 

In [130]:
cars_updated.iloc[13:25, :]

index  company          car_type  wheel-base  length engine-type  \
13     16  Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17  Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18  Kantaka         Salon car        94.5   158.8         ohc   
16     19  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27  Kantaka             Wagon        96.5   157.1         ohc   
19     28  Kantaka         Salon car        96.5   175.4         ohc   
20     29  Kantaka         Salon car        96.5   169.1         ohc   
21     30  Kantaka         Salon car        94.3   170.7         ohc   
24     33  Kantaka         Salon car       113.0   199.6        dohc   
25     34  Kantaka         Salon car       113.0   199.6        dohc   
26     35  Kantaka         Salon car       102.0   191.7        ohcv   

   num-of-cylinders  egine_capacity  average-km     price  
13            three             3.2    75.63898   33481.5  
14             four             4.7    61.15492   40917.5  
15             four             4.7    61.15492   42737.5  
16             four             4.5    49.88954   41450.5  
17             four             4.5    49.88954   40488.5  
18             four             5.1    48.28020   47417.5  
19             four             6.7    38.62416   84142.5  
20             four             6.7    40.23350   67242.5  
21             four             5.2    38.62416   44102.5  
24              six            11.7    24.14010  209625.0  
25              six            11.7    24.14010  231075.0  
26           twelve            17.5    20.92142  234000.0

## e.Count total cars per company 

In [141]:
#Sorting company and car_type from cleaned dataset
mydatset = cars_updated.loc[:, ['company', 'car_type']]
mydatset

company          car_type
0        Honda       Convertible
1        Honda       Convertible
2        Honda  Four Wheel Drive
3      Hyundai         Salon car
4      Hyundai         Salon car
5      Hyundai         Salon car
6      Hyundai             Wagon
7          Bmw         Salon car
8          Bmw         Salon car
9          Bmw         Salon car
10         Bmw         Salon car
11         Bmw         Salon car
12         Bmw         Salon car
13     Kantaka  Four Wheel Drive
14     Kantaka  Four Wheel Drive
15     Kantaka         Salon car
16     Kantaka  Four Wheel Drive
17     Kantaka  Four Wheel Drive
18     Kantaka             Wagon
19     Kantaka         Salon car
20     Kantaka         Salon car
21     Kantaka         Salon car
24     Kantaka         Salon car
25     Kantaka         Salon car
26     Kantaka         Salon car
27       Mazda  Four Wheel Drive
28       Mazda  Four Wheel Drive
29       Mazda  Four Wheel Drive
30       Mazda  Four Wheel Drive
31       Mazda         Salon car
32      Toyota         Salon car
33      Toyota             Wagon
34      Toyota         Salon car
35      Toyota           hardtop
36  Mitsubishi  Four Wheel Drive
37  Mitsubishi  Four Wheel Drive
38  Mitsubishi         Salon car
39  Mitsubishi         Salon car
40      Nissan         Salon car
41      Nissan         Salon car
42      Nissan         Salon car
43      Nissan             Wagon
44      Nissan         Salon car
45  Mitsubishi       Convertible
46  Mitsubishi       Convertible
48       Honda  Four Wheel Drive
49       Honda  Four Wheel Drive
50       Honda  Four Wheel Drive
51       Honda             Wagon
52       Honda             Wagon
53       Honda             Wagon
54       Honda             Wagon
55      Toyota         Salon car
56      Toyota         Salon car
57      Toyota         Salon car
58      Toyota         Salon car
59  Mitsubishi         Salon car
60  Mitsubishi             Wagon

In [142]:
#Count number of cars per company
group = mydatset.groupby('company')
group.count()

car_type
company             
Bmw                6
Honda             10
Hyundai            4
Kantaka           12
Mazda              5
Mitsubishi         8
Nissan             5
Toyota             8

## f.Each company's highest price car

In [213]:
#Grouping by company name
com_group = cars_updated.groupby('company')

#Mapping companies to their highest price cars
com_group[['price']].max()

price
company             
Bmw         268547.5
Honda       107250.0
Hyundai     122980.0
Kantaka     234000.0
Mazda       119236.0
Mitsubishi  240682.0
Nissan       87743.5
Toyota      295100.0

## g.Average milleage of each car making company 

In [214]:
com_group[['company', 'average-km']].mean()

average-km
company               
Bmw          30.577460
Honda        42.164708
Hyundai      32.186800
Kantaka      44.390962
Mazda        45.061520
Mitsubishi   39.831165
Nissan       50.533276
Toyota       40.032333

## h.Sorting all cars by price column

In [224]:
#Sorting cars by price column
cars_updated.sort_values(by=['price'], ascending = False)

index     company          car_type  wheel-base  length engine-type  \
35     47      Toyota           hardtop       112.0   199.2        ohcv   
11     14         Bmw         Salon car       103.5   193.8         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
12     15         Bmw         Salon car       110.0   197.0         ohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
31     43       Mazda         Salon car       104.9   175.0         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
1       1       Honda       Convertible        88.6   168.8        dohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
0       0       Honda       Convertible        88.6   168.8        dohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
56     81      Toyota         Salon car        97.3   171.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
55     80      Toyota         Salon car        97.3   171.7         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four W

## i.Concatenating data frames using dictionary

In [223]:
#Defining dictinaries
GhanaCars = {'Company': ['Kantaka', 'VW', 'BMW', 'Neoplan'], 'Price': [23845, 171995, 135925, 71400]}
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500, 58900]}

#Creating a DataFrame from the dictionaries
Ghacars = pd.DataFrame.from_dict(GhanaCars)
Japcars = pd.DataFrame.from_dict(JapaneseCars)

#Concatenating the two DataFrames
carsdf_concat = pd.concat([Ghacars, Japcars], keys=['Ghana', 'Japan'])
carsdf_concat

Company   Price
Ghana 0     Kantaka   23845
      1          VW  171995
      2         BMW  135925
      3     Neoplan   71400
Japan 0      Toyota   29995
      1       Honda   23600
      2      Nissan   61500
      3  Mitsubishi   58900