# Importing Pandas and Numpy libraries

In [2]:
import numpy as np
import pandas as pd

# Creating two dimentional array

In [3]:
data = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])
print(data)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


# Creating a DataFrame

In [4]:
dataf = pd.DataFrame(data, index=['row1', 'row2', 'row3'],columns=['col1', 'col2', 'col3', 'col4', 'col5', 'col6'])
print(dataf)

      col1  col2  col3  col4  col5  col6
row1     1     2     3     4     5     6
row2     7     8     9    10    11    12
row3    13    14    15    16    17    18


In [6]:
data1 = ([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])

In [8]:
dataf = pd.DataFrame(data1, index=['row1', 'row2', 'row3'],columns=['col1', 'col2', 'col3', 'col4', 'col5', 'col6'])
print(dataf)

      col1  col2  col3  col4  col5  col6
row1     1     2     3     4     5     6
row2     7     8     9    10    11    12
row3    13    14    15    16    17    18


# Creating a dicyionary

In [9]:
region=["Western", "Central", "Greater Accra", "Volta", "Ahafo"]
pop=[2057225, 2859821, 5446237, 1649523, 747227]

In [11]:
dict_reg={'Region':region, 'Population':pop}

In [12]:
pop_reg=pd.DataFrame(dict_reg)
print(pop_reg)

          Region  Population
0        Western     2057225
1        Central     2859821
2  Greater Accra     5446237
3          Volta     1649523
4          Ahafo      747227


# Uploading a CSV file 

In [14]:
scores=pd.read_csv('studentsperformance.csv')
scores

sex ethnicity parental level of education         lunch  \
0    female   group B           bachelor's degree      standard   
1    female   group C                some college      standard   
2    female   group B             master's degree      standard   
3      male   group A          associate's degree  free/reduced   
4      male   group C                some college      standard   
..      ...       ...                         ...           ...   
995  female   group E             master's degree      standard   
996    male   group C                 high school  free/reduced   
997  female   group C                 high school  free/reduced   
998  female   group D                some college      standard   
999  female   group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [15]:
scores.head()

sex ethnicity parental level of education         lunch  \
0  female   group B           bachelor's degree      standard   
1  female   group C                some college      standard   
2  female   group B             master's degree      standard   
3    male   group A          associate's degree  free/reduced   
4    male   group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [16]:
scores.tail()

sex ethnicity parental level of education         lunch  \
995  female   group E             master's degree      standard   
996    male   group C                 high school  free/reduced   
997  female   group C                 high school  free/reduced   
998  female   group D                some college      standard   
999  female   group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86

# Sorting a DataFrame

In [18]:
scores.sort_values('math score', ascending=False)

sex ethnicity parental level of education         lunch  \
962  female   group E          associate's degree      standard   
625    male   group D                some college      standard   
458  female   group E           bachelor's degree      standard   
623    male   group A                some college      standard   
451  female   group E                some college      standard   
..      ...       ...                         ...           ...   
145  female   group C                some college  free/reduced   
787  female   group B                some college      standard   
17   female   group B            some high school  free/reduced   
980  female   group B                 high school  free/reduced   
59   female   group C            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  
962                    none         100            100            100  
625               completed         100             97             99  
458                    none         100            100            100  
623               completed         100             96             86  
451                    none         100             92             97  
..                      ...         ...            ...            ...  
145                    none          22             39             33  
787                    none          19             38             32  
17                     none          18             32             28  
980                    none           8             24             23  
59                     none           0             17             10  

[1000 rows x 8 columns]

# Selecting a column to display

In [19]:
scores[['sex', 'reading score']]

sex  reading score
0    female             72
1    female             90
2    female             95
3      male             57
4      male             78
..      ...            ...
995  female             99
996    male             55
997  female             71
998  female             78
999  female             86

[1000 rows x 2 columns]

# Generating summary statistics from a DataFrame

In [20]:
scores.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Generating a variable from existing rows and columns

In [24]:
english=(scores['reading score'] + scores['writing score'])/2
print(english)

0      73.0
1      89.0
2      94.0
3      50.5
4      76.5
       ... 
995    97.0
996    55.0
997    68.0
998    77.5
999    86.0
Length: 1000, dtype: float64
